// // /*
// //  * This Java source file was generated by the Gradle 'init' task.
// //  */
// package edu.northeastern.cs5500.delivery.controller;

// import static com.google.common.truth.Truth.assertThat;
// import static com.google.common.truth.Truth.assertWithMessage;

// import org.junit.jupiter.api.Test;

// import edu.northeastern.cs5500.delivery.model.Delivery;
// import edu.northeastern.cs5500.delivery.repository.InMemoryRepository;

// class DeliveryControllerTest {
//     @Test
//     void testRegisterCreatesDeliverys() {
//         DeliveryController deliveryController =
//                 new DeliveryController(new InMemoryRepository<Delivery>());
//         assertThat(deliveryController.getDeliverys()).isNotEmpty();
//     }

//     @Test
//     void testRegisterCreatesValidDeliverys() {
//         DeliveryController deliveryController =
//                 new DeliveryController(new InMemoryRepository<Delivery>());

//         for (Delivery delivery : deliveryController.getDeliverys()) {
//             assertWithMessage(delivery.getTitle()).that(delivery.isValid()).isTrue();
//         }
//     }

//     @Test
//     void testCanAddDelivery() {
//         // This test should NOT call register
//         // TODO: implement this test.
//     }

//     @Test
//     void testCanReplaceDelivery() {
//         // This test should NOT call register
//         // TODO: implement this test.
//     }

//     @Test
//     void testCanDeleteDelivery() {
//         // This test should NOT call register
//         // TODO: implement this test
//     }
// }
